modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="reincarnation_plus"
version="0.0.0.1"
displayName="Reincarnation Plus"
credits=""
displayURL=""
authors="skillfi"

[[dependencies.reincarnation_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="ManasCore"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="IsekaiCore"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

