modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="reincarnation_plus"
version="1.0.0.1"
displayName="Reincarnation +"
credits=""
description = "Added Ogres with his evolution"
displayURL=""
authors="skillfi"

[[dependencies.reincarnation_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="manascore"
    mandatory=true
    versionRange="[2.0.15.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

