modLoader="javafml"
loaderVersion="${forgeLoaderVersion}"
license="All Rights Reserved"

[[mods]]
modId="reincarnation_plus"
version="${modVersion}"
displayName="Tensura Addon"
credits=""
displayURL=""
authors="skillfi"

[[dependencies.reincarnation_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="forge"
    mandatory=true
    versionRange="${forgeLoaderVersion}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="geckolib3"
    mandatory=true
    versionRange="${geckolibVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="tensura"
    mandatory=true
    versionRange="${tensuraVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="manascore"
    mandatory=true
    versionRange="${manasCoreVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reincarnation_plus]]
    modId="iceandfire"
    mandatory=true
    versionRange="${iafVersionCheck}"
    ordering="NONE"
    side="BOTH"

